language: node_js
node_js:
  - '12'
branchs:
  only:
    - master
services:
  - docker
env:
  global:
    - IMAGE_NAME=clattanoia/devops:latest
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $IMAGE_NAME .
  - docker push $IMAGE_NAME
addons:
  ssh_known_hosts:
    - 47.92.89.136
before_install:
  - openssl aes-256-cbc -K $encrypted_9a23470cc66b_key -iv $encrypted_9a23470cc66b_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
after_success:
  - ssh travis@47.92.89.136  -o StrictHostKeyChecking=no 
    'cd ~/Awesome-devops && 
    git checkout . &&
    git pull && 
    chmod +x docker_build.sh && 
    ./docker_build.sh'
