language: node_js
node_js:
- '12'
services:
- docker
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t clattanoia/devops:latest .
- docker push clattanoia/devops:latest
before_install:
- openssl aes-256-cbc -K $encrypted_9a23470cc66b_key -iv $encrypted_9a23470cc66b_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
